### ISSUE TITLE
Closing bracket in wrong place?

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion-module-digico-osc#1]
Line 226 - 228 of index.js - closing brace of init_osc() should probably be below this code. It’s above atm.

```
		this.qSocket.on("data", (data) => {
			// console.log("Got: ",data, "from",this.qSocket.options.address);
		});
```

https://www.facebook.com/groups/companion/permalink/2532012290350439/

**Comment by krocheck** [comment]
You want to do the PR to fix @MeestorX ?

**Comment by MeestorX** [comment]
I’m not quite ready to break someone else’s code just yet. ;-)

**Comment by JeffreyDavidsz** [comment]
Funny how I missed that during testing. Thanks for the fix
