### ISSUE TITLE
digico SD11i OSC (IPAD)

### ISSUE THREAD

**Issue by caramin99** [bitfocus/companion-module-digico-osc#6]
digico SD11i
Faders can be selected but
Fader levels cannot be set to the entered value
The rest works fine. thanks for your work!

**Comment by sydneyjd** [comment]
Are you using the latest stable or latest beta? The last PR I did should have a fix for that if you are using the Beta with the Ipad OSC command set, but the latest fixes have not made it into the beta yet. If you are using the stable release with the OSC command set from Digico support i'm not sure what is happening then.

**Comment by caramin99** [comment]
I am using:

Companion Experimental Builds
companion-2.2.0-c13b28a-2814-win64.exe

**Comment by sydneyjd** [comment]
Hey @JeffreyDavidsz, just curious on what the current status of the latest changes making it into a beta is. No rush, just more so curious as to what/if there is something that needs to be done before then. Learning the ropes on my end...
Thank you!

**Comment by JeffreyDavidsz** [comment]
Normally a message on slack in the module_developer group will do. Can you update the version in package.json? Let me know

**Comment by sydneyjd** [comment]
@JeffreyDavidsz I just opened a PR with the version updated in package.json. Not sure if you can squash the commits together, or if it is not a concern. I will make sure to do that in the future on PRs. Thank you for the info by the way.

**Comment by JeffreyDavidsz** [comment]
Updated
